@include('layouts.header')
@include('layouts.top_bar')
@include('layouts.sidebar_left')
@include('layouts.sidebar_menu')
@include('layouts.sidebar_footer')
@include('layouts.breadcrumb')
@yield('content')
@include('layouts.footer')
